### PR TITLE
R 1.2.1

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/52)

connects to vaadin/components-team-tasks#34

### CODE REVIEW

**Comment by cwayfinder** [comment]
The commit #1 ("Use more reliable way to detect when components are ready") is in master already.

**Comment by cwayfinder** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[gulpfile.js, line 121 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2J1bTHiR8h8blBR96_)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/190acc760b685cb7103b6b9a53158342d1678d42/gulpfile.js#L121)):</sup>
Please explain this change


---

<sup>**[gulpfile.js, line 176 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2J20g4wKQ6HTCvAxIF)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/190acc760b685cb7103b6b9a53158342d1678d42/gulpfile.js#L176)):</sup>
Could it be replaced with 
    if (helpers.isBehavior(item)) { 
       parseTemplate('Behavior', item, item.is, '', '');
    } else { 
       parseTemplate('Element', item, item.is, '', 'Element');
    }


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Comment by manolo** [comment]
Review status: 3 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[gulpfile.js, line 121 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2J1bTHiR8h8blBR96_)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/190acc760b685cb7103b6b9a53158342d1678d42/gulpfile.js#L121)):</sup>
It's just a aesthetic change, IDE (Eclipse) complains when a property is named as a reserved word although it's legal in js. I dont think it needs any comment in code.


---

<sup>**[gulpfile.js, line 176 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2J20g4wKQ6HTCvAxIF)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/190acc760b685cb7103b6b9a53158342d1678d42/gulpfile.js#L176)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Comment by Saulis** [comment]
I'm assuming you've tested this version of the generator with gwt-polymer-elements showcase?


---

Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 2 of 8 files at r3, 1 of 1 files at r4, 4 of 5 files at r5, 1 of 1 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[bin/gwt-api-generator.js, line 12 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LZZVCclNBfo5bFqCw)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/105f950c792987d5d97feb526f7b608e9e839810/bin/gwt-api-generator.js#L12)):</sup>
Why isn't package required anymore ?


---

<sup>**[gulpfile.js, line 121 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2J1bTHiR8h8blBR96_)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/190acc760b685cb7103b6b9a53158342d1678d42/gulpfile.js#L121)):</sup>
I'd rather have this as a normal function call. Can't you tell Eclipse to ignore the error?


---

<sup>**[gulpfile.js, line 52 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LX1xDek8dpREONxCN)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/e018b60541c443bbc7df61a3a92a5043c0fc56f0/gulpfile.js#L52)):</sup>
Redundant `done` argument.


---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 278 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LYrCrdfusznbvkglf)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/e018b60541c443bbc7df61a3a92a5043c0fc56f0/lib/com/vaadin/polymer/Polymer.java#L278)):</sup>
Extra whitespace between `static` and `void` 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Comment by manolo** [comment]
Yes I've tested it and I'm working using this branch


---

Review status: 12 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[bin/gwt-api-generator.js, line 12 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LZZVCclNBfo5bFqCw)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/105f950c792987d5d97feb526f7b608e9e839810/bin/gwt-api-generator.js#L12)):</sup>

--package is thought for defining which polymer packages use to generate java classes. Then bower downloads those packages to the resources folder and parses them.  That's perfect for predefined projects like we do in gwt-polymer-elements
Though, I want an easier usage. The gwt user just install bower packages in its java project and run the script each time he wants for instance, if I have the showcase project (demo folder) I just do:

$ bower install vaadin/vaadin-grid#master
$ gwt-api-generator

and voila, I have all the grid wrapped and ready in my src/main/java and src/main/resources
So I'm not deprecating --package argument just not making it mandatory
 


---

<sup>**[gulpfile.js, line 121 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2J1bTHiR8h8blBR96_)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/190acc760b685cb7103b6b9a53158342d1678d42/gulpfile.js#L121)):</sup>
No


---

<sup>**[gulpfile.js, line 52 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LX1xDek8dpREONxCN)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/e018b60541c443bbc7df61a3a92a5043c0fc56f0/gulpfile.js#L52)):</sup>
Done.


---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 278 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LYrCrdfusznbvkglf)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/e018b60541c443bbc7df61a3a92a5043c0fc56f0/lib/com/vaadin/polymer/Polymer.java#L278)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Comment by Saulis** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[bin/gwt-api-generator.js, line 12 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LZZVCclNBfo5bFqCw)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/105f950c792987d5d97feb526f7b608e9e839810/bin/gwt-api-generator.js#L12)):</sup>
OK I see now. Would it be a good idea to add a instructions or some sort of a help message when you run gwt-api-generator without --package and don't have a bower_components folder? Because I tried that nothing just happened - didn't get any log messages or nothing that would tell me what's wrong.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Comment by manolo** [comment]
Review status: 7 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[bin/gwt-api-generator.js, line 12 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LZZVCclNBfo5bFqCw)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/105f950c792987d5d97feb526f7b608e9e839810/bin/gwt-api-generator.js#L12)):</sup>
Modified README


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Comment by Saulis** [comment]
Reviewed 1 of 6 files at r12, 1 of 2 files at r18.
Review status: 8 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[bin/gwt-api-generator.js, line 12 \[r9\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2LZZVCclNBfo5bFqCw)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/105f950c792987d5d97feb526f7b608e9e839810/bin/gwt-api-generator.js#L12)):</sup>
What I had in mind was some kind indicator when you just run the `gwt-api-generator` without any parameters and `bower_components` is empty. Currently nothing just happens.

How about adding a `console.log` messages when generating from a folder? For example: `'No --package provided. Generating 0 package(s) located under bower_components'`


---

<sup>**[gulpfile.js, line 238 \[r18\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2chxPlnOng6Cs27ngc)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/c0333c6872f25cabde6ec309655f2d03c0d13732/gulpfile.js#L238)):</sup>
I think the `else` clause could just be `if (!args.excludeLib)` and the we could get rid of the `done` argument.


---

<sup>**[README.md, line 21 \[r18\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52#-K2ch_s_vJoIcVZHkVo2)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/c0333c6872f25cabde6ec309655f2d03c0d13732/README.md#L21)):</sup>
missing closing ```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/52)

**Pull request merged**
