### PR TITLE
Change namespace to com.vaadin.polymer

### PR DESCRIPTION
**Pull request by Saulis**
Namespaces are now generated using the first part of the element name.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/metathesis/13)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 33 of 38 files at r1.
Review status: 32 of 38 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 129 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-JrqzRK1OcwmYIGPimgn)** ([raw file](https://github.com/vaadin/metathesis/blob/a3cefc72ccdd5babcbacfb0b7f94785f0de22d91/gulpfile.js#L129)):</sup>
I would use just a regexp instead of spliting + regex, it's clearer : obj.name.replace(/-.*$/, '')

---

<sup>**[lib/com/vaadin/polymer/webapi/CSSStyleDeclaration.java, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-Jrr5pByJiuQX9uMkN5e)** ([raw file](https://github.com/vaadin/metathesis/blob/3a2c2ddfb2280e85a685e3cd144880d5ba1e2ddb/lib/com/vaadin/polymer/webapi/CSSStyleDeclaration.java#L1)):</sup>
Should be elemental instead of webapi

---

<sup>**[template/GwtModule.template, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-Jrr67US26-TfKlRsKWH)** ([raw file](https://github.com/vaadin/metathesis/blob/a3cefc72ccdd5babcbacfb0b7f94785f0de22d91/template/GwtModule.template#L3)):</sup>
I think it's an empty value here instead of dot

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/metathesis/13)

**Comment by Saulis** [comment]
Review status: 31 of 38 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 129 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-JrqzRK1OcwmYIGPimgn)** ([raw file](https://github.com/vaadin/metathesis/blob/a3cefc72ccdd5babcbacfb0b7f94785f0de22d91/gulpfile.js#L129)):</sup>
Well.. not sure about it being clearer. Not all of us are Regex experts, I had to look up what `/-.*$/` does with regexer.com :smile: And actually that regex only removed the parts after a dash but didn't replace any dots? Tried with `Polymer.Base`

---

<sup>**[template/GwtModule.template, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-Jrr67US26-TfKlRsKWH)** ([raw file](https://github.com/vaadin/metathesis/blob/a3cefc72ccdd5babcbacfb0b7f94785f0de22d91/template/GwtModule.template#L3)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/metathesis/13)

**Comment by Saulis** [comment]
Review status: 30 of 39 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 129 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-JrqzRK1OcwmYIGPimgn)** ([raw file](https://github.com/vaadin/metathesis/blob/a3cefc72ccdd5babcbacfb0b7f94785f0de22d91/gulpfile.js#L129)):</sup>
I suggest we just use a simple `.replace('.', '')` here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/metathesis/13)

**Comment by manolo** [comment]
Reviewed 4 of 38 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 129 \[r1\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-JrqzRK1OcwmYIGPimgn)** ([raw file](https://github.com/vaadin/metathesis/blob/a3cefc72ccdd5babcbacfb0b7f94785f0de22d91/gulpfile.js#L129)):</sup>
Ah, ok I din't realise the dot thing.

---

<sup>**[lib/com/vaadin/polymer/elemental/CSSStyleDeclaration.java, line 1 \[r2\]](https://reviewable.io:443/reviews/vaadin/metathesis/13#-JrrCpYPg3xg1UzmQWe9)** ([raw file](https://github.com/vaadin/metathesis/blob/f57b9c7a5d2dfd2f54704b057fca9f129a325992/lib/com/vaadin/polymer/elemental/CSSStyleDeclaration.java#L1)):</sup>
I meant that all the webapi should be moved as elemental

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/metathesis/13)

**Comment by Saulis** [comment]
https://reviewable.io/reviews/vaadin/gwt-api-generator/13#-

**Comment by manolo** [comment]
Reviewed 38 of 38 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/13)

**Pull request merged**
