### PR TITLE
Add setter for custom attributes that don't have correspondent proper…

### PR DESCRIPTION
**Pull request by cwayfinder**
…ties in certain polymer elements

[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/32)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/PolymerWidget.java, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32#-JsOkj9fSGfHPInplQuz)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/0f7078dac581fc884d5372a7c189c99bb7f9aa35/lib/com/vaadin/polymer/PolymerWidget.java#L54)):</sup>
Not sure I understand the meaning for the word "Marker" here. Can you elaborate a bit the origin of the method name?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32)

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/PolymerWidget.java, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32#-JsOkj9fSGfHPInplQuz)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/0f7078dac581fc884d5372a7c189c99bb7f9aa35/lib/com/vaadin/polymer/PolymerWidget.java#L54)):</sup>
OK, after reading https://github.com/vaadin/gwt-polymer-elements/pull/29 I understand the context better now. Instead of having an attribute `markerAttributes` in the widgets, I think it should be something like `addAttributes` to reflect the `addStyleNames` we have already there.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32)

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/PolymerWidget.java, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32#-JsOkj9fSGfHPInplQuz)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/0f7078dac581fc884d5372a7c189c99bb7f9aa35/lib/com/vaadin/polymer/PolymerWidget.java#L54)):</sup>
agree, add attributes could be clear enough

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32)

**Comment by cwayfinder** [comment]
Such custom attributes are always boolean. They are just markers. Examples:

1. If the drawer panel find child with marker attribute `paper-drawer-toggle` then it add some click handler.
```
<p:PaperDrawerPanel ui:field="panel">
    <div drawer=""></div>
    <div main="">
        <p:PaperButton ui:field="flipButton" raised="true">flip drawer</p:PaperButton>
        <p:PaperButton markerAttributes="paper-drawer-toggle" raised="true">toggle drawer</p:PaperButton>
    </div>
 </p:PaperDrawerPanel>
```

2. If the item body has the `two-line` marker attribute and it has child with the `secondary` then the `paper-item-icon` applies some styles to them.
```
<p:PaperIconItem>
    <div class="avatar red" item-icon=""/>
    <p:PaperItemBody markerAttributes="two-line">
        <div>Recipes</div>
        <div secondary="">Jan 17, 2014</div>
    </p:PaperItemBody>
     <i:IronIcon icon="star"/>
</p:PaperIconItem>
```

`setAttributes` or `setAddAttributes` would be OK until we have not only boolean custom attributes. I consider those attributes above as special kind of attributes and the word "marker" means what they are.

**Comment by manolo** [comment]
I like more the first approach Taras did allowing non only boolean attributes. And also I like the setAttributes which is more meaningful.
I have restored that feature, is ok for you guys to merge this?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/32)

**Pull request merged**
