### PR TITLE
support both JS & JS_RC modes

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/54)

Connected to vaadin/gwt-polymer-elements#66

### CODE REVIEW

**Comment by manolo** [comment]
Since legacy jsInteropMode=JS has been removed, this PR should support only new syntax.

**Comment by tehapo** [comment]
Review status: 0 of 26 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/com/vaadin/polymer/Polymer.java, line 194 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8Txg7O611XNVONJ6yx:-K8Txg7O611XNVONJ6yy:624046836) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/lib/com/vaadin/polymer/Polymer.java#L194)):*
After this change both branches of the `if` block seem to do about the same thing. Is the `urlImported` set (and the `if` condition) even needed anymore or could this method be simplified a bit?

---

*[package.json, line 3 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8U-0dHJzTrEAGVETP_:-K8U-0dHJzTrEAGVETPa:894701773) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/package.json#L3)):*
Why is the patch version incremented by two? Why not `1.2.2`? Or should this be even `1.3.0`?

---

*[README.md, line 68 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8U0bTKlXpd3XLQQRYD:-K8U0bTKlXpd3XLQQRYE:-148578814) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/README.md#L68)):*
Typo. Should be `support` instead of `suppor`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54)*

**Comment by tomivirkki** [comment]
Contains some more stuff than what the title says (bugfixes, Promise&Template API's, changes to existing API's...). But the code looks ok and compiler seems to produce stuff that works so lgtm (as soon as Teemu's findings are fixed).

---

Review status: 0 of 26 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-:-K8U9tp3qr8YMu464Syr:-1363840705)*

**Comment by tehapo** [comment]
Reviewed 1 of 21 files at r1, 6 of 10 files at r2, 19 of 19 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54)*

**Comment by tehapo** [comment]
Review status: 25 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[package.json, line 3 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8U-0dHJzTrEAGVETP_:-K8YmPI_z_TzV6RcDDuy:-1169580823) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/package.json#L3)):*
This was discussed during our daily meeting. The version reflects Polymer version, so this is ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54)*

**Comment by manolo** [comment]
Yes, the PR has became big because it includes all the work in this long period. Also the title does not reflect the change since we are abandoning legacy syntax instead to support both.

---

Review status: 25 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/com/vaadin/polymer/Polymer.java, line 194 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8Txg7O611XNVONJ6yx:-K8Zg4VdQnxOt7cBtudz:1365956862) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/lib/com/vaadin/polymer/Polymer.java#L194)):*
Actually we have to run importHref so as Polymer takes care of running the ok or err function depending on whether the resource is available. 

I have refactored this method so as we also consider when the element has been registered previously (the user could do in the index.html page, or using vulcanized stuff, etc.)

FYI, this fixes issue #55

---

*[package.json, line 3 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8U-0dHJzTrEAGVETP_:-K8ZkP-8YKhfX6JGQ1wb:1696090716) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/package.json#L3)):*
exactly we match the latest Polymer, that was decided in a meeting with Joonas and Artur some time ago.

---

*[README.md, line 68 \[r3\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-K8U0bTKlXpd3XLQQRYD:-K8ZkZtP_PKKlSI-hHzS:-499146009) ([raw file](https://github.com/vaadin/gwt-api-generator/blob/80d117cc8af1b52f84dec20e523cbf5c2083739d/README.md#L68)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-:-K8ZkpxpaxegSBztxQYR:-303149217)*

**Comment by tehapo** [comment]
LGTM.

---

Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/54#-:-K8Zxd4uOINvKve8CZ4t:-492975211)*

**Pull request merged**
