### PR TITLE
Make generator always generate getters with prefix `get`

### PR DESCRIPTION
**Pull request by cwayfinder**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/20)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[template/helpers.js, line 144 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20#-Js0RqpL5VFo-crNxiug)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/bf1e3a2757b289803d455a4c30382e16c16d33eb/template/helpers.js#L144)):</sup>
Could you specify the case where it was failing, so as we can use that case to check when the bug is fixed

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20)

**Comment by cwayfinder** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[template/helpers.js, line 144 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20#-Js0RqpL5VFo-crNxiug)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/bf1e3a2757b289803d455a4c30382e16c16d33eb/template/helpers.js#L144)):</sup>
the following code
```
    @UiField
    PaperButton button;

    public ButtonSample() {
        initWidget(ourUiBinder.createAndBindUi(ButtonSample.this));
        
        GWT.log("raised: " + button.getRaised());
        button.setRaised(false);
        GWT.log("raised: " + button.getRaised());
        button.setRaised(true);
        GWT.log("raised: " + button.getRaised());
    }
```
should print 
```
raised: true
raised: false
raised: true
```
instead of 
```
raised: undefined
raised: undefined
raised: undefined
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20)

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[template/helpers.js, line 144 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20#-Js0RqpL5VFo-crNxiug)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/bf1e3a2757b289803d455a4c30382e16c16d33eb/template/helpers.js#L144)):</sup>
No I meant document in the code the exact case that made this fail:

  // replaced isXXX methods with getXXX temporary because of bug in JsInterop
  // because in the case of isNarrow, the JS generated is something like $object.arrow 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20)

**Comment by cwayfinder** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[template/helpers.js, line 144 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20#-Js0RqpL5VFo-crNxiug)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/bf1e3a2757b289803d455a4c30382e16c16d33eb/template/helpers.js#L144)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20)

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/20)

**Pull request merged**
