### PR TITLE
Add few methods to web API

### PR DESCRIPTION
**Pull request by cwayfinder**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/38)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/elemental/NodeList.java, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38#-JtImZHI6WnKJhMw6v2k)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/d75a2a196a56bd78ec9aa383a700c0fb9ef0cead/lib/com/vaadin/polymer/elemental/NodeList.java#L7)):</sup>
I would not use generics for this interface, which could make it more restrictive.
I would let the generic T extends Node in the item method

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38)

**Comment by cwayfinder** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/elemental/NodeList.java, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38#-JtImZHI6WnKJhMw6v2k)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/d75a2a196a56bd78ec9aa383a700c0fb9ef0cead/lib/com/vaadin/polymer/elemental/NodeList.java#L7)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38)

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/elemental/NodeList.java, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38#-JtImZHI6WnKJhMw6v2k)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/d75a2a196a56bd78ec9aa383a700c0fb9ef0cead/lib/com/vaadin/polymer/elemental/NodeList.java#L7)):</sup>
You can remove <T> as well. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38)

**Comment by manolo** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/38)

**Pull request merged**
