### PR TITLE
Feature/reload props

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/15)

### CODE REVIEW

**Comment by wolfie** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_1iYUx7nThtJl9iS)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/gulpfile.js#L11)):</sup>
As an reader unfamiliar with this code, I have a hard time guessing what "custom" stands for. The latter use of "custom.customise" is even less understandable.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 102 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_VrOnw3zVCveugBV)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L102)):</sup>
Why not `Scheduler.get().scheduleDeferred`?

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 182 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_yZ4LSpbdEL3akdr)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L182)):</sup>
This javadoc doesn't help me understand this method, because i'm so unfamiliar what this does. But maybe it doesn't matter, since it's still a private method.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 184 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_r8x8e-ZXiovN2Mo)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L184)):</sup>
I think it should be "reassign" instead of "reasign". 

Since the javadoc talks about elements, why not require an element type in the method signature?

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 203 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-JrxaL7Xoh24LYlSkmjp)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L203)):</sup>
Since the javadoc talks about elements, why not require an element type in the method signature?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15)

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_1iYUx7nThtJl9iS)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/gulpfile.js#L11)):</sup>
Well, I dont have any better idea about the naming.
This file is thought as a place to put workarounds needed to adapt files before they are parsed, for instance to correct or add certain annotations.
The first word that came to me was customize because it should be different per library to wrap, these adjustments right now are for wrapping polymer+paper.
You might have a better idea though.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 102 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_VrOnw3zVCveugBV)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L102)):</sup>
Timer is translated into JS using less code than Scheduler, and finally both rely in a setTimeout, so I dont see any advantage to use Scheduler

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 182 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_yZ4LSpbdEL3akdr)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L182)):</sup>
I will try to rewording this.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 184 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_r8x8e-ZXiovN2Mo)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/lib/com/vaadin/polymer/Polymer.java#L184)):</sup>
You're right, will change it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15)

**Comment by Saulis** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_1iYUx7nThtJl9iS)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/gulpfile.js#L11)):</sup>
As suggested in the other comment, it could be named as 'pre-parse' gulp tasks file and exported like that. We wouldn't need to assign it to any variables that way, `require('./template/tasks/pre-parse.js')`would be sufficient.

---

<sup>**[gulpfile.js, line 52 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-JrzwMGuRYCYhMOUnLp0)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/79b21e97413f2e0df4e242b498e86a008a4b65e5/gulpfile.js#L52)):</sup>
Why do we replace these annotations in the first place? Is it related with the boolean JSProperty issue we saw earlier?

---

<sup>**[template/custom.js, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-JrzwfpDzytwTtQvDrlL)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/template/custom.js#L1)):</sup>
Would it make sense to expose these as gulp tasks? That would enable running and debugging them more easily. This file could be called pre-parse.js for example and have a main level gulp task 'pre-parse' with would depend on tasks that we use to fix iron-a11y-keys.html, paper-drawer-panel.html and iron-overlay-behavior.html

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15)

**Comment by manolo** [comment]
Review status: 1 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Jrx_1iYUx7nThtJl9iS)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/gulpfile.js#L11)):</sup>
Done.

---

<sup>**[gulpfile.js, line 52 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-JrzwMGuRYCYhMOUnLp0)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/79b21e97413f2e0df4e242b498e86a008a4b65e5/gulpfile.js#L52)):</sup>
Done.

---

<sup>**[template/custom.js, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-JrzwfpDzytwTtQvDrlL)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/461a521374fd73340c19b17121f63aa79ef355a5/template/custom.js#L1)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15)

**Comment by Saulis** [comment]
Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 214 \[r2\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Js-OjfEV_jzljLIwbnR)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/d3f23865a0f5c03b1432c88ae4110f21013b3905/gulpfile.js#L214)):</sup>
We should probably add the new task as a dependency for the `analyze` task instead? And that raises the question of maybe renaming it to `pre-analyze` ?

---

<sup>**[template/tasks/pre-parse.js, line 11 \[r2\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Js-O9gKwoaxPQnd5lGI)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/d3f23865a0f5c03b1432c88ae4110f21013b3905/template/tasks/pre-parse.js#L11)):</sup>
These variables common with `gulpfile.js` should probably be extracted into `config.js` or `common.js` under the `tasks` folder and used with `require`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15)

**Comment by manolo** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 214 \[r2\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15#-Js-OjfEV_jzljLIwbnR)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/d3f23865a0f5c03b1432c88ae4110f21013b3905/gulpfile.js#L214)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/15)

**Pull request merged**
