### PR TITLE
Generated discaimers contain information about the related component

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/14)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 132 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEXXUvy70p3sGv1Tq)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/gulpfile.js#L132)):</sup>
I would get rid of bowerData parameter since it comes in obj.bowerData

---

<sup>**[template/Element.template, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEhpjHes8msTjYpZb)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/template/Element.template#L1)):</sup>
Use just disclaimer() since helper is executed in the item context

---

<sup>**[template/helpers.js, line 188 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEpK-gP_7b5A5TFDD)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/template/helpers.js#L188)):</sup>
this.bowerData should bring this info

---

<sup>**[template/ImportsMap.template, line 2 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwExnT9wbI9lpAp8Im)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/template/ImportsMap.template#L2)):</sup>
This file was removed, why do you commit again?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14)

**Comment by tomivirkki** [comment]
<sup>**[gulpfile.js, line 132 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEXXUvy70p3sGv1Tq)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/gulpfile.js#L132)):</sup>
In the task "generate:events" it doesn't because event != item. Maybe we could set event.bowerData = item.bowerData instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14)

**Comment by tomivirkki** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[gulpfile.js, line 132 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEXXUvy70p3sGv1Tq)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/gulpfile.js#L132)):</sup>
Done.

---

<sup>**[template/Element.template, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEhpjHes8msTjYpZb)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/template/Element.template#L1)):</sup>
Done.

---

<sup>**[template/helpers.js, line 188 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwEpK-gP_7b5A5TFDD)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/template/helpers.js#L188)):</sup>
Done.

---

<sup>**[template/ImportsMap.template, line 2 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14#-JrwExnT9wbI9lpAp8Im)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/87b28a2a2ee0c49583c361b6793396f3188cec07/template/ImportsMap.template#L2)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14)

**Comment by manolo** [comment]
Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14)

**Comment by Saulis** [comment]
Not sure if this is a deal breaker, but in some cases assigning the `item.bowerData` to `event.bowerData` might lead into some confusing results like this:

```java
/*
 * This code was generated with Vaadin Web Component GWT API Generator, 
 * from paper-toggle-button project by The Polymer Authors
 * that is licensed with http://polymer.github.io/LICENSE.txt license.
 */
package com.vaadin.polymer.iron.element.event;

import com.vaadin.polymer.elemental.*;
import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.js.JsProperty;
import com.google.gwt.core.client.js.JsType;

/**
 * <p>Fired when the checked state changes.</p>
 */
@JsType
public interface IronChangeEvent extends Event {

    static final String NAME = "iron-change";


    public abstract class Listener implements EventListener {
        protected abstract void handleEvent(IronChangeEvent event);

        @Override
        public void handleEvent(Event event) {
            handleEvent((IronChangeEvent) event);
        }
    }
}

```

---

Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/14)

**Pull request merged**
