### PR TITLE
Adding ready functions to Polymer helper classes

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/gwt-api-generator/35)

### CODE REVIEW

**Comment by cwayfinder** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35#-JsdTJhFtfkea7Sc-Eet)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/a033de12b843471844f331d7c689d7ea4eb9f1ae/lib/com/vaadin/polymer/Polymer.java#L64)):</sup>
I think, there could be situation when the `hrefOrTag`  already added to the `urlImported` list but correspondent html file is not completely loaded yet. Can we wrap this line with the `Polymer.ready`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35)

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35#-JsdTJhFtfkea7Sc-Eet)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/a033de12b843471844f331d7c689d7ea4eb9f1ae/lib/com/vaadin/polymer/Polymer.java#L64)):</sup>
good catch

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35)

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35#-JsdTJhFtfkea7Sc-Eet)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/a033de12b843471844f331d7c689d7ea4eb9f1ae/lib/com/vaadin/polymer/Polymer.java#L64)):</sup>
well, forget that, the ready is thought for elements, and not for urls, in this case is ok because the url is loaded. So the code is ok in this way

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35)

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[lib/com/vaadin/polymer/Polymer.java, line 73 \[r1\]](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35#-JsdTJhFtfkea7Sc-Eet)** ([raw file](https://github.com/vaadin/gwt-api-generator/blob/a033de12b843471844f331d7c689d7ea4eb9f1ae/lib/com/vaadin/polymer/Polymer.java#L73)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/gwt-api-generator/35)

**Comment by cwayfinder** [comment]
Can be merged after resolving compilation errors.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project gwt-polymer-elements: Compilation failure: Compilation failure:
[ERROR] /Users/tarashupalo/sandbox/gwt-polymer-elements/src/main/java/com/vaadin/polymer/Polymer.java:[66,25] local variable ok is accessed from within inner class; needs to be declared final
[ERROR] /Users/tarashupalo/sandbox/gwt-polymer-elements/src/main/java/com/vaadin/polymer/Polymer.java:[67,25] local variable ok is accessed from within inner class; needs to be declared final

**Pull request merged**
